Q1. Create the first numpy array of 1-D with values (1,2,3,0). 
Create a second numpy array of 1-D with values (4,1,0, 
6). Perform following simple arithmetic operations on 
these two numpy arrays: 
• Addition 
• Subtraction 
• Multiplication 
• Division 

In [56]:
import numpy as np
import warnings
warnings.filterwarnings("ignore")
arr1 = np.array([1,2,3,0])
print("arr1 = ",arr1,type(arr1))
print("Shape of arr1 = ",arr1.shape)
print("Dimension of arr1 = ",arr1.ndim)
print("*"*40)
arr2 =np.array([4,1,0,6])
print("arr2 = ",arr2,type(arr2))
print("Shape of arr2 = ",arr1.shape)
print("Dimension of arr2 = ",arr1.ndim)
print("*"*40)
print("Addition of two numpy arrays")
print("-"*30)
Add = arr1+arr2
print("Additon :",Add,type(Add))
print("Shape of Additon Output = ",Add.shape)
print("Dimension of Additon Output = ",Add.ndim)
print("*"*40)
print("Subtraction of two numpy arrays")
print("-"*30)
Sub = arr1-arr2
print("Subtraction :",Sub,type(Sub))
print("Shape of Subtraction Output = ",Sub.shape)
print("Dimension of Subtraction Output = ",Sub.ndim)
print("*"*40)
print("Multiplication of two numpy arrays")
print("-"*30)
Mul = arr1*arr2
print("Multiplication :",Mul,type(Mul))
print("Shape of Multiplication Output = ",Mul.shape)
print("Dimension of Multiplication Output = ",Mul.ndim)
print("*"*40)
print("Division of two numpy arrays")
print("-"*30)
Div = np.divide(arr1, arr2, out=np.zeros_like(arr1, dtype=float), where=arr2!=0)
print("Division :",Div,type(Div))
print("Shape of Division Output = ",Div.shape)
print("Dimension of Division Output = ",Div.ndim)
print("*"*40)

arr1 =  [1 2 3 0] <class 'numpy.ndarray'>
Shape of arr1 =  (4,)
Dimension of arr1 =  1
****************************************
arr2 =  [4 1 0 6] <class 'numpy.ndarray'>
Shape of arr2 =  (4,)
Dimension of arr2 =  1
****************************************
Addition of two numpy arrays
------------------------------
Additon : [5 3 3 6] <class 'numpy.ndarray'>
Shape of Additon Output =  (4,)
Dimension of Additon Output =  1
****************************************
Subtraction of two numpy arrays
------------------------------
Subtraction : [-3  1  3 -6] <class 'numpy.ndarray'>
Shape of Subtraction Output =  (4,)
Dimension of Subtraction Output =  1
****************************************
Multiplication of two numpy arrays
------------------------------
Multiplication : [4 2 0 0] <class 'numpy.ndarray'>
Shape of Multiplication Output =  (4,)
Dimension of Multiplication Output =  1
****************************************
Division of two numpy arrays
------------------------------
Division

Q2)Create the first numpy array of random integers 
between 1-100 of 5 elements in 1-D. Create second 
numpy array of 2-D for the same range of integers of 
shape 4*5. Now perform following simple arithmetic 
operations on these two numpy arrays: 
• Addition 
• Subtraction 

In [57]:
import numpy as np
arr1 = np.random.randint(1,100,5)
print("arr1 = ",arr1,type(arr1))
print("Dimension of arr1 = {}-D".format(arr1.ndim))
print("-"*50)
arr2 =np.random.randint(1,100,20).reshape(4,5)
print("arr2 = ")
print(arr2)
print("Dimension of arr2 = {}-D".format(arr2.ndim))
print("-"*50)
print("Addition of two numpy arrays")
print("-"*30)
Add = arr1+arr2
print("Additon :",Add,type(Add))
print("Shape of Additon Output = ",Add.shape)
print("Dimension of Additon Output = ",Add.ndim)
print("*"*40)
print("Subtraction of two numpy arrays")
print("-"*30)
Sub = arr1-arr2
print("Subtraction :",Sub,type(Sub))
print("Shape of Subtraction Output = ",Sub.shape)
print("Dimension of Subtraction Output = ",Sub.ndim)
print("*"*40)

arr1 =  [48 79 38 84 27] <class 'numpy.ndarray'>
Dimension of arr1 = 1-D
--------------------------------------------------
arr2 = 
[[28 84 41 99 44]
 [99 34 18 65 83]
 [82 75 85 98 82]
 [20 10 43 69 95]]
Dimension of arr2 = 2-D
--------------------------------------------------
Addition of two numpy arrays
------------------------------
Additon : [[ 76 163  79 183  71]
 [147 113  56 149 110]
 [130 154 123 182 109]
 [ 68  89  81 153 122]] <class 'numpy.ndarray'>
Shape of Additon Output =  (4, 5)
Dimension of Additon Output =  2
****************************************
Subtraction of two numpy arrays
------------------------------
Subtraction : [[ 20  -5  -3 -15 -17]
 [-51  45  20  19 -56]
 [-34   4 -47 -14 -55]
 [ 28  69  -5  15 -68]] <class 'numpy.ndarray'>
Shape of Subtraction Output =  (4, 5)
Dimension of Subtraction Output =  2
****************************************


Q3)Create a 3-D array of 27 random elements using random 
function of shape 3*3*3. Now pull the following 
elements using indexing/slicing 
• Third column of second 2-D array 
• First and third row of first 2-D array 
• Intersection of first row and third column in 
third 2-D aray 

In [58]:
import numpy as np
arr = np.random.randint(1,100,27).reshape(3,3,3)
print("arr:")
print("*"*40)
print(arr)
print("*"*40)
print("Dimension of arr {}-D".format(arr.ndim))
print("*"*40)

arr:
****************************************
[[[13 55  2]
  [35 98 59]
  [36 40 26]]

 [[56 60 73]
  [89 18 16]
  [91 89 14]]

 [[51 82 29]
  [95 53 93]
  [50 82  9]]]
****************************************
Dimension of arr 3-D
****************************************


In [59]:
print("1) Get Third column of second 2-D array")
print("-"*40)
print(arr[1][:,2:])
print("*"*40)
print("2) Get  First and third row of first 2-D array")
print("-"*40)
print(arr[1][:,0:3:2])
print("*"*40)
print("3) Get Intersection of first row and third column in third 2-D aray")
print("-"*40)
print(arr[2][:1:1,2:])
print("*"*40)

1) Get Third column of second 2-D array
----------------------------------------
[[73]
 [16]
 [14]]
****************************************
2) Get  First and third row of first 2-D array
----------------------------------------
[[56 73]
 [89 16]
 [91 14]]
****************************************
3) Get Intersection of first row and third column in third 2-D aray
----------------------------------------
[[29]]
****************************************


Q4 ) Create a 2-D numpy array of random integers between 
1 to 100 with shape 5*4. Now perform following 
operations: 
• Print only the even numbers from this array 
• Print only the odd numbers from this array 
• Print row wise sum of all elements 
• Print column wise sum of all elements 
• Convert this 2-D array into 3-D array of shape 
2*2*5

In [60]:
import numpy as np
arr = np.random.randint(1,100,20).reshape(5,4)
print("arr:")
print(arr)
print("*"*50)
print("Dimesion of arr {}-D".format(arr.ndim))
print("*"*50)

arr:
[[ 6 62 16 36]
 [99 41 53 24]
 [51 99 53  3]
 [48 77 43  9]
 [99 88 36 66]]
**************************************************
Dimesion of arr 2-D
**************************************************


In [61]:
def iseven(n):
    return n%2==0

In [62]:
print("1) Print only the even numbers from this array")
print("Output:",arr[np.where(iseven(arr))])
print("-"*40)
print("2) Print only the odd numbers from this array")
print("Output:",arr[np.where(~iseven(arr))])
print("-"*40)
print("3) Print row wise sum of all elements")
print("Output:",arr.sum(axis=0))
print("-"*40)
print("4) Print column wise sum of all elements")
print("Output:",arr.sum(axis=1))
print("-"*40)
print("5) Convert this 2-D array into 3-D array of shape 2*2*5")
print("Output:")
print(arr.reshape(2,2,5))
print("Dimension of Output {}-D".format(arr.reshape(2,2,5).ndim))
print("-"*40)

1) Print only the even numbers from this array
Output: [ 6 62 16 36 24 48 88 36 66]
----------------------------------------
2) Print only the odd numbers from this array
Output: [99 41 53 51 99 53  3 77 43  9 99]
----------------------------------------
3) Print row wise sum of all elements
Output: [303 367 201 138]
----------------------------------------
4) Print column wise sum of all elements
Output: [120 217 206 177 289]
----------------------------------------
5) Convert this 2-D array into 3-D array of shape 2*2*5
Output:
[[[ 6 62 16 36 99]
  [41 53 24 51 99]]

 [[53  3 48 77 43]
  [ 9 99 88 36 66]]]
Dimension of Output 3-D
----------------------------------------


Q5. Create a 2-D numpy array of random integers between 
1 to 100 with shape 5*4. Now perform following 
operations: 
• Swap first row with third row 
• Swap second column with fourth column. 
• Replace the values less than 50 with zero. 
• Convert this 2D array into 1-D array 

In [63]:
import numpy as np
arr = np.random.randint(1,100,20).reshape(5,4)
print("Output:")
print(arr)
print("Dimension of arr {}-D".format(arr.ndim))

Output:
[[69 19 94 38]
 [59  5 25 66]
 [49 25 12 75]
 [75 45 93 63]
 [97 70 16 94]]
Dimension of arr 2-D


In [64]:
print("1) Swap first row with third row")
print("-"*40)
print("Array before row Swaping:")
print(arr)
print("-"*40)
arr[[0,2]]=arr[[2,0]]
print("Array after row Swaping:")
print(arr)

1) Swap first row with third row
----------------------------------------
Array before row Swaping:
[[69 19 94 38]
 [59  5 25 66]
 [49 25 12 75]
 [75 45 93 63]
 [97 70 16 94]]
----------------------------------------
Array after row Swaping:
[[49 25 12 75]
 [59  5 25 66]
 [69 19 94 38]
 [75 45 93 63]
 [97 70 16 94]]


In [65]:
print("2) Swap second column with fourth column.")
print("-"*40)
print("Array before column Swaping:")
print(arr)
print("-"*40)
arr[:,[1,3]]=arr[:,[3,1]]
print("Array after column Swaping:")
print(arr)

2) Swap second column with fourth column.
----------------------------------------
Array before column Swaping:
[[49 25 12 75]
 [59  5 25 66]
 [69 19 94 38]
 [75 45 93 63]
 [97 70 16 94]]
----------------------------------------
Array after column Swaping:
[[49 75 12 25]
 [59 66 25  5]
 [69 38 94 19]
 [75 63 93 45]
 [97 94 16 70]]


In [66]:
def val(n):
    if n<50:
        return 0

In [67]:
print("3) Replace the values less than 50 with zero.")
print("-"*40)
print("Array before replaceing the value:")
print(arr)
print("-"*40)
print("Array after replaceing the value:")
replace_arr = np.where(arr<50,0,arr)
print(replace_arr)

3) Replace the values less than 50 with zero.
----------------------------------------
Array before replaceing the value:
[[49 75 12 25]
 [59 66 25  5]
 [69 38 94 19]
 [75 63 93 45]
 [97 94 16 70]]
----------------------------------------
Array after replaceing the value:
[[ 0 75  0  0]
 [59 66  0  0]
 [69  0 94  0]
 [75 63 93  0]
 [97 94  0 70]]


In [69]:
print("4) Convert this 2D array into 1-D array")
print("-"*40)
print(arr)
print("Dimension of arr : {}-D".format(arr.ndim))
print("-"*40)
Convert_arr =np.ravel(arr)
print(Convert_arr)
print("Dimension of Convert_arr : {}-D".format(Convert_arr.ndim))

4) Convert this 2D array into 1-D array
----------------------------------------
[[49 75 12 25]
 [59 66 25  5]
 [69 38 94 19]
 [75 63 93 45]
 [97 94 16 70]]
Dimension of arr : 2-D
----------------------------------------
[49 75 12 25 59 66 25  5 69 38 94 19 75 63 93 45 97 94 16 70]
Dimension of Convert_arr : 1-D


Q6. Explain the concept of stacking in numpy with examples. 
How is it different from concatenation. Give any 3 
differences between them. 

##### Example of Stacking

In [87]:
import numpy as np

stack1 = np.arange(1,20,4)
stack2 = np.random.randint(1,50,5)
print("stack1: {} Type: {} Dimension: {}-D".format(stack1,type(stack1),stack1.ndim))
print("stack2: {} Type: {} Dimension: {}-D".format(stack2,type(stack2),stack2.ndim))
print("*"*70)
print("*"*70)
Stacking_row = np.stack((stack1,stack2))
print("Stacking_row:")
print(Stacking_row)
print("Type: {} Dimension: {}-D Shape:{}".format(type(Stacking_row),Stacking_row.ndim,Stacking_row.shape))
print("*"*70)
print("*"*70)
Stacking_col = np.stack((stack1,stack2),axis=1)
print("Stacking_row:")
print(Stacking_col)
print("Type: {} Dimension: {}-D Shape:{}".format(type(Stacking_col),Stacking_col.ndim,Stacking_col.shape))

stack1: [ 1  5  9 13 17] Type: <class 'numpy.ndarray'> Dimension: 1-D
stack2: [25 22 19 37 14] Type: <class 'numpy.ndarray'> Dimension: 1-D
**********************************************************************
**********************************************************************
Stacking_row:
[[ 1  5  9 13 17]
 [25 22 19 37 14]]
Type: <class 'numpy.ndarray'> Dimension: 2-D Shape:(2, 5)
**********************************************************************
**********************************************************************
Stacking_row:
[[ 1 25]
 [ 5 22]
 [ 9 19]
 [13 37]
 [17 14]]
Type: <class 'numpy.ndarray'> Dimension: 2-D Shape:(5, 2)


In [90]:
import numpy as np

stack1 = np.arange(1,20,4)
stack2 = np.random.randint(1,50,5)
print("stack1: {} Type: {} Dimension: {}-D".format(stack1,type(stack1),stack1.ndim))
print("stack2: {} Type: {} Dimension: {}-D".format(stack2,type(stack2),stack2.ndim))
print("*"*70)
print("*"*70)
Concat = np.concatenate((stack1,stack2))
print("Concat:",Concat)
print("Type: {} Dimension: {}-D Shape:{}".format(type(Concat),Concat.ndim,Concat.shape))

stack1: [ 1  5  9 13 17] Type: <class 'numpy.ndarray'> Dimension: 1-D
stack2: [41 42 25 11 19] Type: <class 'numpy.ndarray'> Dimension: 1-D
**********************************************************************
**********************************************************************
Concat: [ 1  5  9 13 17 41 42 25 11 19]
Type: <class 'numpy.ndarray'> Dimension: 1-D Shape:(10,)
